### ISSUE TITLE
Download Links down?

### ISSUE THREAD

**Issue by Curlykonda** [nathanshartmann/portuguese_word_embeddings#14]
Hi 

As I tried to download the trained Word Embeddings provided on the NILC [website](http://nilc.icmc.usp.br/nilc/index.php/repositorio-de-word-embeddings-do-nilc), it seems that the download links are down, i.e. no connection to the files on the server. 

Could you check this issue and make the embeddings available again? 

Thank you

**Comment by nathanshartmann** [comment]
All download links are online. Please, try to download it again from another network.
