### ISSUE TITLE
Acesso ao dataset de treinamento

### ISSUE THREAD

**Issue by bratao** [nathanshartmann/portuguese_word_embeddings#17]
Olá tudo bem? @nathanshartmann 

Sou pesquisador da Universidade Federal da Bahia, e estou juntando um dataset para treinar alguns modelos de transformers como o ALBERT e REFORMER. O modelo será publicado e os devidos creditos obviamente serão dados. 
Você pode compartilhar o dataset utilizado comigo?

Meu email é bruno-at-potelo.com.br

**Comment by nathanshartmann** [comment]
Boa tarde. Tudo bem?

Estamos feliz em anunciar que a parcela pública do dataset está disponível para download em http://nilc.icmc.usp.br/embeddings
