### ISSUE TITLE
Pre-trained models broken links

### ISSUE THREAD

**Issue by adaj** [nathanshartmann/portuguese_word_embeddings#2]
Hi there!

I am trying to download the pre-trained models available on [this link](http://nilc.icmc.usp.br/embeddings) but maybe the server is in troubles. Could you provide any solution? 

Thanks in advance!

**Comment by nathanshartmann** [comment]
Hello there, 

I just tested here and all urls work fine. Please, try it again and notify me if the problem persists.

Best regards.

**Comment by adaj** [comment]
I tested again, same prob. Maybe the link is internal for USP servers.

**Comment by nathanshartmann** [comment]
Hello again.

It is strange. I am able to download all models at home.
May i make any embedding model available to you? Google drive for example. Just let me know.

[]`s,

**Comment by adaj** [comment]
Actually, I tried in a third network and I succeed. That's ok there, thanks for the checking! Closing.

**Comment by luishenriquesb** [comment]
Hi there! 

This problem came back
I'd like to obtain the GloVe Word Embeddings files, but I can't

@nathanshartmann could you share the "GLOVE 1000 dimensões" file with me? We can use google drive. My email is luis.brito@serpro.gov.br.

Thanks

**Comment by iagocc** [comment]
I'm trying to download now, and the links still broken for me, is it correct?
