### ISSUE TITLE
Ainda é possível acessar as Word Embeddings Pré-treinadas pelo gensim diretamente?

### ISSUE THREAD

**Issue by guilhermeparreira** [nathanshartmann/portuguese_word_embeddings#20]
Olá. eu estou tentando obter uma word embedding pré treinada conforme a instrução de vocês:

```
pip install gensim==2.0.0
from gensim.models import KeyedVectors
#model = KeyedVectors.load_word2vec_format(‘model.txt’)
```

Mas na 2ª linha me retorna um erro que eu não consegui resolver:
`ImportError: cannot import name 'logsumexp' from 'scipy.misc' (/databricks/python/lib/python3.7/site-packages/scipy/misc/__init__.py)`

Eu tentei instalar a versão mais recente do gensim mas obtive um erro similar. Eu consigo ainda obter essas word embeddings por dentro do python/pelo gensim?

**Comment by brunoedcf** [comment]
Opa amigo, conseguiu resolver esse erro de alguma forma? To tendo o mesmo problema

**Comment by guilhermeparreira** [comment]
não consegui

**Comment by nathanshartmann** [comment]
Boa tarde, pessoal.

É possível sim. Testei aqui utilizando a versão '3.8.1' do gensim e importou normalmente. Acredito que a versão '2.0.0', da época que disponibilizei as embedding, está dando conflito com outros pacotes. Sugiro utilizarem versão mais recente do gensim.
