### ISSUE TITLE
Trained Word2Vec models

### ISSUE THREAD

**Issue by miguelwon** [nathanshartmann/portuguese_word_embeddings#8]
Hi,
I would like to know if you have the trained Word2Vec models (.bin). I want to perform online training with an additional corpus I have but would like to start with you pre-trained model. Unfortunately using `gensim.models.KeyedVectors` does not create a model able to be retrained.

**Comment by nathanshartmann** [comment]
Sorry, but we only have the models already available. We did not save the weights of the neural network for fine-tuning to be possible. Again, I apologize for the design failure.
